language: python
python:
  #- "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - "pip install -U importlib_metadata"
  - "python setup.py install"
script: nosetests
